
server:
  port: 9095
spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/market_order
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka